name: Build Klein

on:
  workflow_dispatch:
  
jobs:
  qmk_build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        ref: ${{ github.event.inputs.branch || github.ref }}

    - name: Install dependencies
      run: pip3 install -r requirements.txt


    - name: QMK setup
      run: qmk setup -y
    - name: Build Klein
      run: qmk compile -kb snsten/klein -km default
    - name: Upload the generated hex file
      uses: actions/upload-artifact@v2
      with:
        name: hex_file
        path: snsten_klein_default.hex
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: hex_file
