name: Build Klein

on:
  workflow_dispatch:
  
jobs:
  qmk_build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
    - uses: actions/checkout@v2
    - name: QMK setup
      run: qmk setup -y
    - name: Build Klein
      run: qmk compile -kb snsten/klein -km default
    - name: Upload the generated hex file
      uses: actions/upload-artifact@v2
      with:
        name: hex_file
        path: snsten_klein.hex
    - name: Download math result for job 2
      uses: actions/download-artifact@v2
      with:
        name: hex_file
